site_name: Saeed Sabet
site_description: A site about me and my work.
site_url: "https://saeedsabet.com"
site_description: "Official Website of Saeed Sabet"
repo_url: https://github.com/sssabet
repo_name: sssabet



nav:
    - Home: index.md
    - About: about.md
    - Skills: skills.md
    - Projects: projects.md
    - Research:
        - 'My First Post': 'blog/2024-09-30-my-first-post.md'


theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.png
  icon:
    repo: material/github
    logo: octicons/cpu-16

  font:
    text: Inter
    code: Noto Sans Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow
    - navigation.top

  palette:
    # Automatically switches between light & dark modes based on system
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/circle-half-full
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/circle-half-full
        name: Switch to light mode


extra_css:
    - stylesheets/custom.css

plugins:
    - search
    - blog:
        blog_dir: blog

markdown_extensions:
  - tables
  - admonition

extra:
  cli: "python saeed.py"
